---
title: Luca Bruno
description: Personal pages
baseurl: ''
url: ''
username: lucab
fullname: Luca Bruno
user_title: Luca Bruno - Personal
email: lucab@debian.org
twitter_username: lucabruno
github_username: lucab
markdown: kramdown
highlighter: rouge
permalink: "/:title/"
exclude:
- package.json
- src
- node_modules
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false
collections:
  projects:
    output: true
links:
- title: home
  url: "/"
- title: about me
  url: "/about"
- title: posts
  url: "/posts"
- title: series
  url: "/series"
- title: tags
  url: "/tags"
projects:
- name: LUA engine for MAME scripting
  url: "/projects/mame-lua"
timezone: Etc/UTC
