---
title: Luca Bruno
short: LB
description: Luca Bruno - Personal pages
baseurl: ''
url: ''
username: lucab
fullname: Luca Bruno
user_title: Luca Bruno - Personal
email: lucab@debian.org
twitter_username: lucabruno
github_username: lucab
markdown: kramdown
highlighter: rouge
permalink: "/:title/"
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false
defaults:
- scope:
    path: _posts
    type: posts
  values:
    permalink: "/posts/:title/"
    layout: post
collections:
  projects:
    output: true
    permalink: "/:collection/:title/"
links:
- title: home
  url: "/"
- title: about me
  url: "/about"
- title: posts
  url: "/posts"
- title: projects
  url: "/projects"
- title: tags
  url: "/tags"
exclude:
- package.json
- src
- node_modules
- LICENSE
timezone: Etc/UTC
